
import React, { useState, useEffect } from 'react';
import { Workspace } from './pages/Workspace';
import { FineTuningDashboard } from './components/FineTuningDashboard';
import { Settings } from './components/Settings';
import { AudioStudio } from './components/AudioStudio';
import { MediaStudio } from './components/MediaStudio';
import { Login } from './components/Login';
import { AppView, Project, ProjectType, SocialPost, AudioTrack, FileNode } from './types';
import { MOCK_PROJECTS, MOCK_SOCIAL_POSTS, WEB_FILE_TREE, NATIVE_FILE_TREE, NODE_FILE_TREE } from './constants';
import { LayoutGrid, Code, Settings as SettingsIcon, Zap, Plus, Search, X, Smartphone, Globe, Server, Trash2, LogOut, Music, Clapperboard, Youtube, Twitter, Instagram, Film, Volume2, Wand2, Loader2, Rocket } from 'lucide-react';
import { Button } from './components/Button';
import { generateProjectScaffold } from './services/geminiService';

const App: React.FC = () => {
  const [isAuthenticated, setIsAuthenticated] = useState(() => {
    return localStorage.getItem('omni_auth') === 'true';
  });
  const [currentView, setCurrentView] = useState<AppView>(AppView.DASHBOARD);
  
  // Initialize projects from localStorage or fallback to mock
  const [projects, setProjects] = useState<Project[]>(() => {
    const saved = localStorage.getItem('omni_projects');
    return saved ? JSON.parse(saved) : MOCK_PROJECTS;
  });
  
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [showNewProjectModal, setShowNewProjectModal] = useState(false);

  // Persist projects whenever they change
  useEffect(() => {
    localStorage.setItem('omni_projects', JSON.stringify(projects));
  }, [projects]);

  const handleLogin = () => {
    localStorage.setItem('omni_auth', 'true');
    setIsAuthenticated(true);
  };

  const handleLogout = () => {
    localStorage.removeItem('omni_auth');
    setIsAuthenticated(false);
    setSelectedProject(null);
    setCurrentView(AppView.DASHBOARD);
  };

  const handleProjectSelect = (project: Project) => {
    setSelectedProject(project);
    setCurrentView(AppView.WORKSPACE);
  };

  const handleCreateProject = async (name: string, type: ProjectType, description: string) => {
    const projectId = Date.now().toString();
    let initialFiles: FileNode[] = [];

    if (description.trim()) {
      // AI Generation
      const generatedNodes = await generateProjectScaffold(description, type);
      
      // Fallback if AI fails
      if (generatedNodes && generatedNodes.length > 0) {
        // Add IDs recursively to generated nodes
        const addIds = (nodes: any[]): FileNode[] => {
           return nodes.map(n => ({
              ...n,
              id: Math.random().toString(36).substr(2, 9),
              gitStatus: 'added',
              children: n.children ? addIds(n.children) : undefined,
              isOpen: n.type === 'directory' // Auto-open generated folders
           }));
        };
        initialFiles = addIds(generatedNodes);
      } else {
         // If API failed, fallback to templates
         initialFiles = type === ProjectType.REACT_NATIVE ? NATIVE_FILE_TREE : type === ProjectType.NODE_API ? NODE_FILE_TREE : WEB_FILE_TREE;
      }
    } else {
      // Standard Template
      initialFiles = type === ProjectType.REACT_NATIVE ? NATIVE_FILE_TREE : type === ProjectType.NODE_API ? NODE_FILE_TREE : WEB_FILE_TREE;
    }

    // Save initial files to storage
    localStorage.setItem(`omni_files_${projectId}`, JSON.stringify(initialFiles));

    const newProject: Project = {
      id: projectId,
      name: name || 'Untitled Project',
      description: description || `A new ${type} application generated by Omni-Studio.`,
      type: type,
      lastModified: 'Just now',
      fileCount: initialFiles.length + (initialFiles[0]?.children?.length || 0)
    };

    setProjects([newProject, ...projects]);
    setSelectedProject(newProject);
    setShowNewProjectModal(false);
    setCurrentView(AppView.WORKSPACE);
  };
  
  const handleDeleteProject = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (confirm('Are you sure you want to delete this project?')) {
      setProjects(projects.filter(p => p.id !== id));
      // Also clean up file storage
      localStorage.removeItem(`omni_files_${id}`);
      if (selectedProject?.id === id) {
        setSelectedProject(null);
      }
    }
  };

  // Sidebar Navigation
  const Sidebar = () => (
    <div className="w-16 bg-gray-950 border-r border-gray-800 flex flex-col items-center py-4 gap-4 z-20 flex-shrink-0">
      <div className="w-10 h-10 bg-primary-600 rounded-xl flex items-center justify-center shadow-lg mb-4">
        <Zap className="text-white" size={24} fill="currentColor" />
      </div>

      <NavIcon 
        icon={<LayoutGrid size={20} />} 
        active={currentView === AppView.DASHBOARD} 
        onClick={() => setCurrentView(AppView.DASHBOARD)} 
        label="Dashboard"
      />
      <NavIcon 
        icon={<Code size={20} />} 
        active={currentView === AppView.WORKSPACE} 
        onClick={() => {
             if (selectedProject) setCurrentView(AppView.WORKSPACE);
             else alert("Please select a project from the dashboard first.");
        }} 
        label="Workspace"
      />
      <div className="w-8 border-t border-gray-800 my-1"></div>
      <NavIcon 
        icon={<Zap size={20} />} 
        active={currentView === AppView.FINETUNE} 
        onClick={() => setCurrentView(AppView.FINETUNE)} 
        label="Fine-Tune"
      />
      <NavIcon 
        icon={<Music size={20} />} 
        active={currentView === AppView.AUDIO} 
        onClick={() => setCurrentView(AppView.AUDIO)} 
        label="Audio Studio"
      />
      <NavIcon 
        icon={<Clapperboard size={20} />} 
        active={currentView === AppView.MEDIA} 
        onClick={() => setCurrentView(AppView.MEDIA)} 
        label="Media Studio"
      />
      
      <div className="mt-auto flex flex-col gap-4">
        <NavIcon 
          icon={<SettingsIcon size={20} />} 
          active={currentView === AppView.SETTINGS} 
          onClick={() => setCurrentView(AppView.SETTINGS)} 
          label="Settings"
        />
        <button 
          onClick={handleLogout}
          className="p-3 rounded-xl text-gray-500 hover:bg-red-900/20 hover:text-red-400 transition-all"
          title="Sign Out"
        >
          <LogOut size={20} />
        </button>
      </div>
    </div>
  );

  const NavIcon = ({ icon, active, onClick, label }: any) => (
    <button 
      onClick={onClick}
      className={`p-3 rounded-xl transition-all duration-200 group relative ${
        active ? 'bg-gray-800 text-primary-500' : 'text-gray-500 hover:bg-gray-900 hover:text-gray-300'
      }`}
    >
      {icon}
      <span className="absolute left-14 top-1/2 transform -translate-y-1/2 bg-gray-800 text-white text-xs px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-50 pointer-events-none border border-gray-700 shadow-xl">
        {label}
      </span>
    </button>
  );

  const NewProjectModal = () => {
    const [name, setName] = useState('');
    const [type, setType] = useState<ProjectType>(ProjectType.REACT_WEB);
    const [description, setDescription] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    const handleCreate = async () => {
        if (description) setIsGenerating(true);
        await handleCreateProject(name, type, description);
        setIsGenerating(false);
    };

    return (
      <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50">
        <div className="bg-gray-900 border border-gray-800 rounded-2xl w-full max-w-md overflow-hidden shadow-2xl p-6">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-semibold text-white">Create New Project</h2>
            <button onClick={() => setShowNewProjectModal(false)} className="text-gray-500 hover:text-white">
              <X size={20} />
            </button>
          </div>
          
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-400 mb-1">Project Name</label>
              <input 
                type="text" 
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g., Super App" 
                className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white focus:border-primary-500 focus:outline-none" 
                autoFocus
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-400 mb-2">Project Type</label>
              <div className="grid grid-cols-1 gap-3">
                <button 
                  onClick={() => setType(ProjectType.REACT_WEB)}
                  className={`flex items-center p-3 rounded-lg border transition-all ${
                    type === ProjectType.REACT_WEB ? 'bg-primary-900/20 border-primary-500 ring-1 ring-primary-500' : 'bg-gray-800 border-gray-700 hover:bg-gray-750'
                  }`}
                >
                  <div className={`p-2 rounded-md mr-3 ${type === ProjectType.REACT_WEB ? 'bg-primary-500 text-white' : 'bg-gray-700 text-gray-400'}`}>
                    <Globe size={18} />
                  </div>
                  <div className="text-left">
                    <div className="text-sm font-medium text-white">React Web</div>
                    <div className="text-xs text-gray-500">Next.js, Tailwind, WebContainers</div>
                  </div>
                </button>

                <button 
                  onClick={() => setType(ProjectType.REACT_NATIVE)}
                  className={`flex items-center p-3 rounded-lg border transition-all ${
                    type === ProjectType.REACT_NATIVE ? 'bg-primary-900/20 border-primary-500 ring-1 ring-primary-500' : 'bg-gray-800 border-gray-700 hover:bg-gray-750'
                  }`}
                >
                  <div className={`p-2 rounded-md mr-3 ${type === ProjectType.REACT_NATIVE ? 'bg-purple-500 text-white' : 'bg-gray-700 text-gray-400'}`}>
                    <Smartphone size={18} />
                  </div>
                  <div className="text-left">
                    <div className="text-sm font-medium text-white">React Native</div>
                    <div className="text-xs text-gray-500">Expo, Mobile Simulator, iOS/Android</div>
                  </div>
                </button>
                
                <button 
                  onClick={() => setType(ProjectType.NODE_API)}
                  className={`flex items-center p-3 rounded-lg border transition-all ${
                    type === ProjectType.NODE_API ? 'bg-primary-900/20 border-primary-500 ring-1 ring-primary-500' : 'bg-gray-800 border-gray-700 hover:bg-gray-750'
                  }`}
                >
                   <div className={`p-2 rounded-md mr-3 ${type === ProjectType.NODE_API ? 'bg-green-500 text-white' : 'bg-gray-700 text-gray-400'}`}>
                    <Server size={18} />
                  </div>
                  <div className="text-left">
                    <div className="text-sm font-medium text-white">Node.js API</div>
                    <div className="text-xs text-gray-500">Express, REST APIs, Microservices</div>
                  </div>
                </button>
              </div>
            </div>

            <div>
                <label className="block text-sm font-medium text-gray-400 mb-1 flex items-center gap-2">
                    <Wand2 size={14} className="text-primary-400" /> 
                    AI Description (Optional)
                </label>
                <textarea 
                   value={description}
                   onChange={(e) => setDescription(e.target.value)}
                   placeholder="Describe your app (e.g., 'A minimalist Todo app with dark mode and local storage'). Leave empty for default template."
                   className="w-full h-20 bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white text-sm focus:border-primary-500 focus:outline-none resize-none"
                />
            </div>
          </div>

          <div className="mt-8 flex gap-3">
             <Button variant="secondary" className="flex-1" onClick={() => setShowNewProjectModal(false)}>Cancel</Button>
             <Button className="flex-1" onClick={handleCreate} disabled={isGenerating}>
                {isGenerating ? <Loader2 size={16} className="animate-spin mr-2" /> : <Rocket size={16} className="mr-2" />}
                {isGenerating ? 'Designing...' : 'Create & Open'}
             </Button>
          </div>
        </div>
      </div>
    );
  }

  const Dashboard = () => {
    const [activeTab, setActiveTab] = useState<'all' | 'code' | 'media' | 'audio'>('all');
    const [recentMedia, setRecentMedia] = useState<SocialPost[]>([]);
    const [recentAudio, setRecentAudio] = useState<AudioTrack[]>([]);

    useEffect(() => {
       const savedMedia = localStorage.getItem('omni_social_posts');
       if (savedMedia) setRecentMedia(JSON.parse(savedMedia));
       else setRecentMedia(MOCK_SOCIAL_POSTS); // Fallback to mock for demo
       
       const savedAudio = localStorage.getItem('omni_audio_tracks');
       if (savedAudio) setRecentAudio(JSON.parse(savedAudio));
    }, []);

    return (
      <div className="flex-1 bg-gray-950 overflow-y-auto p-8 w-full">
        <div className="max-w-6xl mx-auto">
          <div className="flex justify-between items-end mb-8">
            <div>
              <h1 className="text-3xl font-bold text-white mb-2">Welcome back, Creator</h1>
              <p className="text-gray-400">Unified control center for your Code, Media, and Audio projects.</p>
            </div>
            <div className="flex gap-2">
               <Button onClick={() => { setCurrentView(AppView.MEDIA) }} variant="secondary">
                 <Clapperboard size={16} className="mr-2" /> New Content
               </Button>
               <Button onClick={() => setShowNewProjectModal(true)}>
                 <Plus size={16} className="mr-2" /> New Code Project
               </Button>
            </div>
          </div>

          {/* Stats Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-10">
             <div className="bg-gray-900 p-6 rounded-xl border border-gray-800">
                <div className="text-gray-500 text-sm font-medium mb-1">Active Projects</div>
                <div className="text-2xl font-bold text-white">{projects.length} <span className="text-sm text-gray-500 font-normal">Code</span></div>
             </div>
             <div className="bg-gray-900 p-6 rounded-xl border border-gray-800">
                <div className="text-gray-500 text-sm font-medium mb-1">Social Reach</div>
                <div className="text-2xl font-bold text-white">{recentMedia.length} <span className="text-sm text-gray-500 font-normal">Posts</span></div>
             </div>
             <div className="bg-gray-900 p-6 rounded-xl border border-gray-800">
                <div className="text-gray-500 text-sm font-medium mb-1">Audio Assets</div>
                <div className="text-2xl font-bold text-white">{recentAudio.length} <span className="text-sm text-gray-500 font-normal">Tracks</span></div>
             </div>
          </div>

          {/* Tabs */}
          <div className="flex gap-6 mb-6 border-b border-gray-800">
             {['all', 'code', 'media', 'audio'].map(tab => (
                <button 
                  key={tab}
                  onClick={() => setActiveTab(tab as any)}
                  className={`pb-3 text-sm font-medium capitalize transition-colors relative ${activeTab === tab ? 'text-primary-500' : 'text-gray-500 hover:text-white'}`}
                >
                   {tab === 'all' ? 'All Projects' : tab}
                   {activeTab === tab && <div className="absolute bottom-0 left-0 w-full h-0.5 bg-primary-500 rounded-t-full"></div>}
                </button>
             ))}
          </div>

          {/* Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {(activeTab === 'all' || activeTab === 'code') && projects.map(project => (
              <div 
                key={project.id} 
                onClick={() => handleProjectSelect(project)}
                className="group bg-gray-900 border border-gray-800 rounded-xl p-6 cursor-pointer hover:border-primary-600/50 hover:shadow-2xl hover:shadow-primary-900/20 transition-all duration-300 relative overflow-hidden"
              >
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary-600 to-purple-600 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                <div className="flex justify-between items-start mb-4">
                   <div className={`p-2 rounded-lg ${
                      project.type === ProjectType.REACT_NATIVE ? 'bg-purple-900/30 text-purple-400' : 
                      project.type === ProjectType.NODE_API ? 'bg-green-900/30 text-green-400' :
                      'bg-blue-900/30 text-blue-400'
                   }`}>
                       {project.type === ProjectType.REACT_NATIVE ? <Smartphone size={20} /> : 
                        project.type === ProjectType.NODE_API ? <Server size={20} /> : 
                        <Globe size={20} />}
                   </div>
                   <div className="flex items-center gap-2">
                      <span className="text-xs text-gray-500">{project.lastModified}</span>
                      <button 
                        onClick={(e) => handleDeleteProject(e, project.id)}
                        className="text-gray-600 hover:text-red-400 transition-colors p-1"
                      >
                        <Trash2 size={14} />
                      </button>
                   </div>
                </div>
                <h3 className="text-lg font-semibold text-white mb-2 group-hover:text-primary-400 transition-colors">{project.name}</h3>
                <p className="text-sm text-gray-400 mb-4 line-clamp-2">{project.description}</p>
                <div className="flex items-center gap-2 text-xs text-gray-500">
                   <span className="px-2 py-1 bg-gray-800 rounded border border-gray-700">{project.type}</span>
                   <span>•</span>
                   <span>{project.fileCount} files</span>
                </div>
              </div>
            ))}

            {(activeTab === 'all' || activeTab === 'media') && recentMedia.map(post => (
              <div 
                key={post.id} 
                onClick={() => setCurrentView(AppView.MEDIA)}
                className="group bg-gray-900 border border-gray-800 rounded-xl p-0 cursor-pointer hover:border-pink-600/50 hover:shadow-2xl hover:shadow-pink-900/20 transition-all duration-300 relative overflow-hidden flex flex-col"
              >
                <div className="h-32 w-full bg-gray-800 relative overflow-hidden">
                    {post.thumbnail ? (
                        <img src={post.thumbnail} className="w-full h-full object-cover opacity-60 group-hover:opacity-100 transition-opacity" alt="thumb" />
                    ) : (
                        <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-gray-800 to-gray-900">
                           <Clapperboard className="text-gray-600" size={32} />
                        </div>
                    )}
                    <div className={`absolute top-3 right-3 p-1.5 rounded-lg bg-black/50 backdrop-blur ${
                        post.platform === 'youtube' ? 'text-red-400' : 
                        post.platform === 'twitter' ? 'text-blue-400' : 
                        'text-pink-400'
                    }`}>
                        {post.platform === 'youtube' && <Youtube size={16} />}
                        {post.platform === 'twitter' && <Twitter size={16} />}
                        {post.platform === 'tiktok' && <Film size={16} />}
                        {post.platform === 'instagram' && <Instagram size={16} />}
                    </div>
                </div>
                <div className="p-5 flex-1 flex flex-col">
                   <h3 className="text-md font-semibold text-white mb-2 group-hover:text-pink-400 transition-colors line-clamp-1">{post.title}</h3>
                   <div className="mt-auto flex justify-between items-center">
                      <span className={`text-[10px] px-2 py-0.5 rounded-full uppercase font-bold ${
                          post.status === 'uploaded' ? 'bg-green-900/30 text-green-400' : 'bg-yellow-900/30 text-yellow-400'
                      }`}>
                         {post.status}
                      </span>
                      {post.views && <span className="text-xs text-gray-500">{post.views} views</span>}
                   </div>
                </div>
              </div>
            ))}

            {(activeTab === 'all' || activeTab === 'audio') && recentAudio.map(track => (
               <div 
                 key={track.id}
                 onClick={() => setCurrentView(AppView.AUDIO)}
                 className="group bg-gray-900 border border-gray-800 rounded-xl p-6 cursor-pointer hover:border-purple-600/50 hover:shadow-2xl hover:shadow-purple-900/20 transition-all duration-300 relative overflow-hidden"
               >
                 <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-purple-600 to-blue-600 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                 <div className="flex justify-between items-start mb-4">
                    <div className="p-2 rounded-lg bg-purple-900/30 text-purple-400">
                        {track.type === 'music' ? <Music size={20} /> : <Volume2 size={20} />}
                    </div>
                    <div className="flex items-center gap-1 text-gray-500">
                       <div className="flex gap-0.5 h-4 items-end">
                          {[1,2,3,4,5].map(i => <div key={i} className="w-0.5 bg-gray-600" style={{height: `${Math.random() * 100}%`}}></div>)}
                       </div>
                    </div>
                 </div>
                 <h3 className="text-lg font-semibold text-white mb-2 group-hover:text-purple-400 transition-colors truncate">{track.name}</h3>
                 <div className="flex items-center gap-2 text-xs text-gray-500">
                    <span className="capitalize">{track.type}</span>
                    <span>•</span>
                    <span>{Math.floor(track.duration)}s</span>
                 </div>
               </div>
            ))}
          </div>
        </div>
      </div>
    );
  };

  if (!isAuthenticated) {
    return <Login onLogin={handleLogin} />;
  }

  return (
    <div className="flex h-screen w-screen bg-gray-950 text-gray-100 font-sans selection:bg-primary-500/30 overflow-hidden">
      <Sidebar />
      
      {showNewProjectModal && <NewProjectModal />}
      
      {currentView === AppView.DASHBOARD && <Dashboard />}
      {currentView === AppView.WORKSPACE && <Workspace project={selectedProject} />}
      {currentView === AppView.FINETUNE && <FineTuningDashboard />}
      {currentView === AppView.AUDIO && <AudioStudio />}
      {currentView === AppView.MEDIA && <MediaStudio />}
      {currentView === AppView.SETTINGS && <Settings />}
    </div>
  );
};

export default App;
