
import React, { useState, useEffect } from 'react';
import { Workspace } from './pages/Workspace';
import { FineTuningDashboard } from './components/FineTuningDashboard';
import { Settings } from './components/Settings';
import { AudioStudio } from './components/AudioStudio';
import { MediaStudio } from './components/MediaStudio';
import { Login } from './components/Login';
import { Dashboard } from './components/Dashboard';
import { AppView, Project, ProjectType, FileNode } from './types';
import { MOCK_PROJECTS } from './constants';
import { Menu } from 'lucide-react';
import { Button } from './components/Button';
import { TeamManager } from './components/TeamManager';
import { NewProjectModal } from './components/NewProjectModal';
import { AppSidebar } from './components/AppSidebar';

const App: React.FC = () => {
  const [isAuthenticated, setIsAuthenticated] = useState(() => {
    return localStorage.getItem('omni_auth') === 'true';
  });
  
  const [currentView, setCurrentView] = useState<AppView>(() => {
      return (localStorage.getItem('omni_current_view') as AppView) || AppView.DASHBOARD;
  });
  
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  
  // Initialize projects from localStorage or fallback to mock
  const [projects, setProjects] = useState<Project[]>(() => {
    const saved = localStorage.getItem('omni_projects');
    return saved ? JSON.parse(saved) : MOCK_PROJECTS;
  });
  
  const [selectedProject, setSelectedProject] = useState<Project | null>(() => {
      const saved = localStorage.getItem('omni_active_project');
      return saved ? JSON.parse(saved) : null;
  });

  const [showNewProjectModal, setShowNewProjectModal] = useState(false);
  const [showTeamManager, setShowTeamManager] = useState(false);

  // Persist state
  useEffect(() => {
    localStorage.setItem('omni_projects', JSON.stringify(projects));
  }, [projects]);

  useEffect(() => {
      localStorage.setItem('omni_current_view', currentView);
  }, [currentView]);

  useEffect(() => {
      if (selectedProject) localStorage.setItem('omni_active_project', JSON.stringify(selectedProject));
      else localStorage.removeItem('omni_active_project');
  }, [selectedProject]);

  const handleLogin = () => {
    localStorage.setItem('omni_auth', 'true');
    setIsAuthenticated(true);
  };

  const handleLogout = () => {
    localStorage.removeItem('omni_auth');
    setIsAuthenticated(false);
    setSelectedProject(null);
    setCurrentView(AppView.DASHBOARD);
  };

  const handleProjectSelect = (project: Project) => {
    setSelectedProject(project);
    setCurrentView(AppView.WORKSPACE);
  };

  const handleCreateProject = (name: string, type: ProjectType, description: string, initialFiles: FileNode[]) => {
    const projectId = Date.now().toString();
    
    // Save initial files to storage
    localStorage.setItem(`omni_files_${projectId}`, JSON.stringify(initialFiles));

    const newProject: Project = {
      id: projectId,
      name: name || 'Untitled Project',
      description: description || `A new ${type} application generated by Omni-Studio.`,
      type: type,
      lastModified: 'Just now',
      fileCount: initialFiles.length + (initialFiles[0]?.children?.length || 0)
    };

    setProjects([newProject, ...projects]);
    setSelectedProject(newProject);
    setShowNewProjectModal(false);
    setCurrentView(AppView.WORKSPACE);
  };
  
  const handleDeleteProject = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    if (confirm('Are you sure you want to delete this project?')) {
      setProjects(projects.filter(p => p.id !== id));
      localStorage.removeItem(`omni_files_${id}`);
      if (selectedProject?.id === id) {
        setSelectedProject(null);
      }
    }
  };

  const handleNavClick = (view: AppView) => {
      if (view === AppView.WORKSPACE && !selectedProject) {
          alert("Please select a project from the dashboard first.");
          return;
      }
      setCurrentView(view);
      setIsMobileMenuOpen(false);
  };

  if (!isAuthenticated) {
    return <Login onLogin={handleLogin} />;
  }

  return (
    <div className="flex h-screen w-screen bg-gray-950 text-gray-100 font-sans selection:bg-primary-500/30 overflow-hidden flex-col md:flex-row">
      {/* Mobile Top Bar */}
      <div className="md:hidden h-14 border-b border-gray-800 flex items-center px-4 bg-gray-950 sticky top-0 z-40 justify-between shrink-0">
         <div className="flex items-center">
             <button onClick={() => setIsMobileMenuOpen(true)} className="p-2 text-gray-400 -ml-2">
               <Menu size={24} />
             </button>
             <span className="ml-2 font-bold text-white">Omni-Studio</span>
         </div>
         {currentView !== AppView.DASHBOARD && (
             <span className="text-xs font-mono text-primary-400 bg-primary-900/20 px-2 py-1 rounded">{currentView}</span>
         )}
      </div>

      <AppSidebar 
        currentView={currentView} 
        onNavigate={handleNavClick} 
        onLogout={handleLogout} 
        isOpen={isMobileMenuOpen}
        setIsOpen={setIsMobileMenuOpen}
      />
      
      {showNewProjectModal && (
        <NewProjectModal 
            onClose={() => setShowNewProjectModal(false)} 
            onCreate={handleCreateProject} 
        />
      )}
      {showTeamManager && <TeamManager onClose={() => setShowTeamManager(false)} />}
      
      <div className="flex-1 flex flex-col min-w-0 h-full overflow-hidden relative">
          {currentView === AppView.DASHBOARD && (
              <div className="relative flex-1 flex flex-col overflow-hidden bg-gray-950">
                  <Dashboard 
                      projects={projects} 
                      onProjectSelect={handleProjectSelect} 
                      onDeleteProject={handleDeleteProject} 
                      onNewProject={() => setShowNewProjectModal(true)}
                      onNavigate={handleNavClick}
                      onManageTeam={() => setShowTeamManager(true)}
                  />
              </div>
          )}
          {currentView === AppView.WORKSPACE && <Workspace project={selectedProject} />}
          {currentView === AppView.FINETUNE && <FineTuningDashboard />}
          {currentView === AppView.AUDIO && <AudioStudio />}
          {currentView === AppView.MEDIA && <MediaStudio />}
          {currentView === AppView.SETTINGS && <Settings />}
      </div>
    </div>
  );
};

export default App;
